added new code routing
dainst/erga pull request #12
Opened 2020-11-03 16:17 UTC by preiaen

Es sind eigentlich nur zwei kleine Änderungen, aber es arbeitet viel mit Error Handling und ist vielleicht nicht der Elixir-Weg, deshalb schaut es euch mal an.

Diese Änderung funktioniert nach einem Code-first Prinzip, zuerst wird versucht den Parameter als Code zu verwenden, wenn das scheitert, wird versucht den "Code" als ID zu benutzen und so den Code zu erhalten. Wenn das auch nicht geht, dann ist es offensichtlich weder Code noch ID. In diesem Fall wird man zum Index umgeleitet und es wird ein Fehler ausgegeben. 

Das hat den Vorteil das alte Routes mit der ID erhalten bleiben in der Browser URL aber immer die URL mit dem ProjectCode steht.

Ich habe jetzt mit einem richtigen und einem falschen Code getestet, sowie mit einer richtigen und einer falschen ID.

2020-11-06 06:51 UTC, dersmon commented
Ok, das ist nice hacky. Theoretisch könnte man aber auf die Nase fallen, wenn jemand eine Nummer als Code verwendet oder?

2020-11-09 09:08 UTC, preiaen commented
Ja genau, wenn man eine Project Code verwendet, der einer bestehenden ID entspricht, würde man bei einem Aufruf der Links die noch mit der bestehenden Project-ID arbeiten, auf das neue Project gelangen. Man könnte aber immer noch über den ProjectCode auf die eigene Projectseite gelangen. Insgesamt glaube ich aber, dass dieses Problem in der Praxis nicht besteht, da 99.9 % der Projecte einen Alphanumerischen Code verwenden. Wir sollten aber dafür sorgen, dass nur noch Links mit Code verwendet werden und die ID wirklich nur als Fallback exisitiert.

2020-11-09 14:29 UTC, preiaen commented
Habe es nun so geändert wie besprochen

2020-11-10 10:19 UTC, dersmon requested changes
Kann es sein, dass man um vom project :index auf :show gehen zu können die URL noch um den language Parameter erweitert werden muss? Bei mir versucht der http://localhost:4000/projects/1 aufzurufen, meldet dann aber Project ID not found.

2020-11-10 10:19 UTC, dersmon commented on lib/erga/research.ex
> +    end
Was macht die Funktion?

2020-11-10 10:54 UTC, dersmon approved these changes

2020-11-10 11:12 UTC, dersmon commented on lib/erga/research.ex
> +    end
bzw. wozu braucht es die Funktion? Decken die zwei Funktionen darüber nicht schon alles ab?

2020-11-10 14:22 UTC, merged