Person MVC von Phoenix LiveView zu Standard
dainst/erga pull request #16
Opened 2020-11-19 09:27 UTC by dersmon

2020-11-19 09:28 UTC, dersmon commented
Es gibt jetzt auch einen neuen Menüpunkt "Manage" neben der Möglichkeit neue persons anzulegen, wenn man einen Stakeholder editiert. Bei "Manage" kann man wiederum persons editieren oder löschen und bekommt angezeigt in welchen Projekten die eingebunden sind.

2020-11-23 09:29 UTC, preiaen commented
Bitte noch die LiveTests löschen / anpassen.

2020-11-24 09:48 UTC, preiaen commented on lib/erga/staff.ex
> +    |> Repo.preload(stakeholders: [:project])
Läd das nur die Projectdaten in den Stakeholders vor?

2020-11-24 09:52 UTC, preiaen requested changes
Abgesehen von den fehlenden Tests sieht alles gut aus.

2020-11-27 12:37 UTC, dersmon commented on lib/erga/staff.ex
> +    |> Repo.preload(stakeholders: [:project])
Nein, das läd die Stakeholder UND deren verknüpfte Projekte.

2020-11-27 12:38 UTC, merged