Evaluate updated at recursively
dainst/erga pull request #21
Opened 2020-11-27 12:31 UTC by dersmon

Dies ist eine Variante zu Ninos Lösung, es wird das updated_at der Projekts jedesmal evaluiert, wenn man das Projekt speichert. Dadurch sparen wir uns, allen anderen model beizubringen das zugehörige Projekt anzupassen.

2020-11-27 12:32 UTC, dersmon commented
Alternative: https://github.com/dainst/erga/pull/13

2020-11-27 15:15 UTC, neuged commented
Finde die Variante ok, Ninos eigentlich auch. Hätte es insgesamt vermutlich auch vorgezogen, wenn die Logik in der Abfrage ist, weilche Projekte da als geändert zurückgibt, wie du das auch bei #13 vermerkt hast, Simon, aber wenn man das bei jedem Update prüft, dann finde ich es so ganz gut.

2020-11-27 15:16 UTC, neuged approved these changes

2020-11-27 15:22 UTC, njunghans commented
Den einzigen unterschied den ich zu meiner lösung sehe, ist das wenn man direkt die anderen tabellen ändert und nicht über die projekt seite selbst, das updated_at nicht verändert wird. Sehe ich das richtig ? Aber wenn ich in der translation tabelle den titel ändere, sollte das project nicht ein neues updated_at bekommen =?

2020-11-30 06:24 UTC, dersmon commented
> Den einzigen unterschied den ich zu meiner lösung sehe, ist das wenn man direkt die anderen tabellen ändert und nicht über die projekt seite selbst, das updated_at nicht verändert wird. Sehe ich das richtig ? Aber wenn ich in der translation tabelle den titel ändere, sollte das project nicht ein neues updated_at bekommen =?

Ja, man muss das Projekt speichern damit es neugesetzt wird.

2020-11-30 06:32 UTC, dersmon commented
Und man muss halt nicht bei jeder Manipulation der abhängigen Daten daran denken das Projekt zu ändern.

Ah, und ein weiterer Vorteil: Da translated_content nicht an projects gebunden ist, kann man da deine Lösung nicht so einfach umsetzen.

2020-11-30 09:50 UTC, preiaen requested changes
So wie es jetzt ist, muss man weiterhin händisch etwas anpassen, wenn man etwas an der Struktur ändert.

2020-11-30 09:50 UTC, preiaen commented on lib/erga/research.ex
> +        get_all_updated_at(project.titles),
diese Liste von get_all_updated_at könnte man auch generisch gestalten, dann wäre es für zukünftige Updates besser gerüstet. Anstatt die Items von Project einzeln aufzurufen, könnte man eine Schleife wie in get_all_updated machen und schauen ob diese eine updated_at Attribut habe. Das könnte man auch direkt in der Funktionssignatur über einen Patternmatch machen.

2020-11-30 09:51 UTC, neuged commented
Hey, also ich habe gerade nochmal versucht, ob man nicht auch einen komplexeren SQL-Query bauen könnte, um die geänderten Projekte zu finden. Was hieltet ihr von so etwas:

```elixir
date = ~N[2020-11-01 00:00:00]
query =
  Project
  |> join(:left, [p], s in assoc(p, :stakeholders))
  |> join(:left, [p], l in assoc(p, :linked_resources))
  |> where([p, s, l], p.updated_at >= ^date
                      or s.updated_at >= ^date
                      or l.updated_at >= ^date)
  |> select([p], p.id)
```

Würde noch etwas länger werden mit den weiteren joins. Vorteil wäre da halt, das man gar nichts updaten müsste.

2020-11-30 09:52 UTC, preiaen commented
Insgesamt finde ich diese Lösung besser, da man nur noch an einer Stelle etwas einbauen muss.

2020-11-30 09:55 UTC, njunghans commented
eine weitere idee, wäre eine weitere tabelle mit updated_at und project_id zu erschaffen und diese zu pflegen.

2020-11-30 13:34 UTC, dersmon commented
> Hey, also ich habe gerade nochmal versucht, ob man nicht auch einen komplexeren SQL-Query bauen könnte, um die geänderten Projekte zu finden. Was hieltet ihr von so etwas:
> 
> 
> 
> ```elixir
> 
> date = ~N[2020-11-01 00:00:00]
> 
> query =
> 
>   Project
> 
>   |> join(:left, [p], s in assoc(p, :stakeholders))
> 
>   |> join(:left, [p], l in assoc(p, :linked_resources))
> 
>   |> where([p, s, l], p.updated_at >= ^date
> 
>                       or s.updated_at >= ^date
> 
>                       or l.updated_at >= ^date)
> 
>   |> select([p], p)
> 
> ```
> 
> 
> 
> Würde noch etwas länger werden mit den weiteren joins. Vorteil wäre da halt, das man gar nichts updaten müsste. Performant ist es auch. Wird alles in einem Query abgehandelt.

Viel besser. Ich hatte kurz mal rumprobiert aber die Syntax die ich dann hatte war ziemlich hässlich. Sowas wie deinen Code hatte ich mir vorgestellt.

2020-11-30 13:39 UTC, preiaen commented
> Hey, also ich habe gerade nochmal versucht, ob man nicht auch einen komplexeren SQL-Query bauen könnte, um die geänderten Projekte zu finden. Was hieltet ihr von so etwas:
> 
> ```elixir
> date = ~N[2020-11-01 00:00:00]
> query =
>   Project
>   |> join(:left, [p], s in assoc(p, :stakeholders))
>   |> join(:left, [p], l in assoc(p, :linked_resources))
>   |> where([p, s, l], p.updated_at >= ^date
>                       or s.updated_at >= ^date
>                       or l.updated_at >= ^date)
>   |> select([p], p)
> ```
> 
> Würde noch etwas länger werden mit den weiteren joins. Vorteil wäre da halt, das man gar nichts updaten müsste. Performant ist es auch. Wird alles in einem Query abgehandelt.

Sowas auf datenbank ebene zu machen, finde ich persönlich auch immer schick. Allerdings ändert deine Lösung nichts an dem ursprünglichen Problem des Wartungsaufwandes. 

Ideal wäre, wenn man einen Loop hätte der alle Relationen durchläuft, die updated_at Felder sucht und die dann auswertet. 

> > Hey, also ich habe gerade nochmal versucht, ob man nicht auch einen komplexeren SQL-Query bauen könnte, um die geänderten Projekte zu finden. Was hieltet ihr von so etwas:
> > ```elixir
> > date = ~N[2020-11-01 00:00:00]
> > 
> > query =
> > 
> >   Project
> > 
> >   |> join(:left, [p], s in assoc(p, :stakeholders))
> > 
> >   |> join(:left, [p], l in assoc(p, :linked_resources))
> > 
> >   |> where([p, s, l], p.updated_at >= ^date
> > 
> >                       or s.updated_at >= ^date
> > 
> >                       or l.updated_at >= ^date)
> > 
> >   |> select([p], p)
> > ```
> > 
> > 
> > Würde noch etwas länger werden mit den weiteren joins. Vorteil wäre da halt, das man gar nichts updaten müsste. Performant ist es auch. Wird alles in einem Query abgehandelt.
> 
> Viel besser. Ich hatte kurz mal rumprobiert aber die Syntax die ich dann hatte war ziemlich hässlich. Sowas wie deinen Code hatte ich mir vorgestellt.

Es bliebe aber das Problem, dass man es jedes mal händisch anpassen müsste. Ich sehe hier eherlich gesagt keinen Vorteil. Es ist im Grund deine jetzige Lösung in SQL übersetzt.

2020-12-01 06:37 UTC, dersmon commented
Nicht ganz. Bei meiner Lösung muss man auf jeden Fall einmal das Projekt speichern. Wenn man im Interface also zum Beispiel eine neue linked_resource hinzufügt und dann den Tab schließt, ist die zwar hinzugefügt aber das Datum des Projektes nicht geupdatedd.

2020-12-01 07:01 UTC, dersmon commented on lib/erga/research.ex
> +    |> join(:left, [p, t, d, s], pe in assoc(s, :person))
Das hatte mich zuvor gestört: Ich dachte man muss für jeden folgenden JOIN alle Variablen noch einmal deklarieren. Stattdessen muss man es nur hier, weil ich die Variable aus der Pipe eins darüber brauche.

2020-12-01 09:21 UTC, njunghans approved these changes

2020-12-01 10:18 UTC, neuged approved these changes

2020-12-01 12:04 UTC, preiaen commented on lib/erga/research.ex
> +    |> join(:left, [p, t, d, s], pe in assoc(s, :person))
Ich verstehe die Zeile nicht ganz. Wieso brauchst du Titel und Description in dem Join?

2020-12-01 12:09 UTC, preiaen approved these changes
Habe nur eine Verständnisfrage.

2020-12-01 12:18 UTC, njunghans commented on lib/erga/research.ex
> +    |> join(:left, [p, t, d, s], pe in assoc(s, :person))
die müssen auch auf update datum überprüft werden

2020-12-01 13:12 UTC, dersmon commented on lib/erga/research.ex
> +    |> join(:left, [p, t, d, s], pe in assoc(s, :person))
Das liegt daran, dass das eine Pipe ist, würde ich direkt [s] machen, wäre s das Project und nicht der Stakeholder. Um mir t und d zu sparen hätte ich auch einfach die Abfrage nach Stakeholders zu erst machen können. Dann wäre die Zeile nur [t, s].

2020-12-01 13:13 UTC, dersmon commented on lib/erga/research.ex
> +    |> join(:left, [p, t, d, s], pe in assoc(s, :person))
Darüber war ich ursprünglich auch gestolpert.

2020-12-01 13:14 UTC, merged