translated content for linked_resource
dainst/erga pull request #24
Opened 2020-12-05 10:49 UTC by njunghans

2020-12-07 11:45 UTC, dersmon commented
Ah mist, jetzt gibt es zweimal "redirect" in der URL und das sorgt für Probleme. Einmal vom Translated content zurück zur linked resource und dann von linked resource zurück zu project.

Hm...

2020-12-15 10:43 UTC, neuged approved these changes
Sieht gut aus für mich. Bin noch nicht so drin in Erga und Elixir, sodass sich das vielleicht auch noch jemand anders anschauen sollte, aber der Code ist verständlich und klar.

2020-12-15 12:02 UTC, dersmon requested changes
Bei mir funktioniert das im Interface nicht richtig. Nur wenn ich eine seeded Linked Resource editiere?

2020-12-21 08:35 UTC, preiaen commented on lib/erga_web/templates/linked_resource/form.html.leex
> +        <%= submit "Save" %>
Warum ist das disabled rausgeflogen?

2020-12-21 08:37 UTC, preiaen requested changes
Sieht soweit alles gut aus, nur dass es keine Tests gibt. Laufen die trotz dieser Änderungen noch durch?

2020-12-23 07:56 UTC, dersmon commented
Das ist noch nicht fertig. Ich hatte angefangen etwas umzubauen, aktuell kann man zwar im Interface übersetzte Beschreibungen anlegen, diese werden aber noch nicht gespeichert.

2021-01-06 12:50 UTC, dersmon commented
Ich habe gerade auch die `list_` Funktionen in research.ex für external links, linked resources und stakeholder gelöscht, weil die (außer in den automatisch von Phoenix generierten Tests) nicht benutzt wurden.

2021-01-06 12:55 UTC, dersmon commented on lib/erga_web/live/linked_resource_live/event_handler.ex
> +        update(socket, String.to_existing_atom(target), fn _ -> params[target] end)
Refactor: Ich fand die "string in list" `cond` nicht so schön.

2021-01-06 12:59 UTC, dersmon commented on lib/erga_web/live/linked_resource_live/event_handler.ex
> +      |> update(:search_result, fn _ -> [] end)
Das diff ist etwas komisch formatiert: 

Es wird jetzt nur noch evaluiert, wenn speichern geklickt wird (einheitlicher mit dem Rest der Anwendung). Deshalb ist die `validate` Funktion rausgeflogen.

Außerdem habe ich wo möglich `update` genommen statt assign, um klar zu machen dass da bereits ein Wert sein sollte. Nur bei der Initialisierung wird `assign` genutzt (siehe `mount` Funktionen in der `linked_resources_live.ex`)

2021-01-06 13:00 UTC, dersmon commented on lib/erga_web/templates/linked_resource/form.html.leex
> +    <%= if assigns[:linked_resource] do %>
Beschreibungsblock wird nur angezeigt, wenn linked resource bereits in Datenbank angelegt wurde.

2021-01-06 13:02 UTC, dersmon commented on lib/erga_web/templates/linked_resource/form.html.leex
> +        <% end %>
Ähnlich wie bei `projects` gibt es jetzt zwei Schritte: Kernfelder anlegen und anschließend optional die Beschreibungen als _Translated Content_. Für den _Translated Content_ braucht es einen bestehenden Tabelleneintrag der _Linked Resource_.

2021-01-08 10:57 UTC, dersmon approved these changes

2021-01-08 11:03 UTC, dersmon commented on lib/erga/research.ex
> -
War schon länger deprecated.

2021-01-08 11:03 UTC, dersmon commented on lib/erga/research.ex
> -
War schon länger deprecated.

2021-01-08 11:03 UTC, dersmon commented on lib/erga/research.ex
> -
War schon länger deprecated.

2021-01-11 12:45 UTC, merged