Neue Suche für den Thesaurus
dainst/erga pull request #36
Opened 2021-04-06 16:50 UTC by preiaen

Ich habe die Thesaurus-Suche jetzt versuchsweise auf den Hierarchiebaum des idaiWorld Thesaurus umgebaut. 

Zur Compile-Zeit wird dafür die gesamte Hierarchie unter dem concept "idai.World Thesaurus" geladen. Zur Laufzeit wird dann nur noch eine Sparqlabfrage an diesen Baum abgesetzt. 
Der gesamte Response ist dafür in einem Modul-Attribute des ThesaurusService gespeichert. 

Mögliche Problem, deren tatsächliche Relevanz ich gerade nicht absehen kann:

Der Speicher müllt voll.
Änderungen am Hierarchiebaum werden ggf. verspätet oder gar nicht in Erga sichtbar.

2021-04-07 08:21 UTC, preiaen commented
Ein weiterer Nachteil dieser Methode ist, dass ein Rückgabewert {:error ...} nicht vernünftig behandelt werden kann. Zur Laufzeit kann ein Modulattribut nicht neu geladen werden. 

Das sicherste wäre eigentlich den Baum einmal pro Sitzung zu laden und dann wiederholt zu nutzen, kann man in Phoenix die Session nutzen?

2021-04-07 10:29 UTC, preiaen commented
Die aktuelle Lösung gefällt mit am Besten und gibt uns für die Zukunft auch weitere Optionen. 
Ich habe [Cachex](https://hexdocs.pm/cachex/getting-started.html) hinzugefügt, dadurch kann man nun überall Daten cachen. Die Daten bleiben 8 Stunden im Cache und werden dann gelöscht. Beim Aufruf des Thesaurus werden die Daten entweder aus dem Cache abgerufen oder, wenn sie nicht da sind, über den Webservice abgefragt und hier gespeichert.

2021-04-16 06:41 UTC, dersmon requested changes
Bis auf die Sache mit dem Filter top. :+1:

2021-04-16 06:41 UTC, dersmon commented on lib/erga_web/live/linked_resource_live.ex
> +    filter = if socket.assigns.linked_system == "thesaurus", do: %{use_hierarchy: true}, else: filter
"just for testing"? Sollte das noch raus?

2021-04-16 06:41 UTC, dersmon commented on lib/erga_web/services/thesaurus_service.ex
>    def get_list(val, _filter) do
Braucht es die Funktion überhaupt noch? 
bzw.  
Wozu braucht man für Thesaurus überhaupt noch den Filterparameter? Könnte man den nicht per default ignorieren, d.h. den Inhalt der neuen Funktion oben in die Funktion hier packen? Dann könnte man sich auch die Änderung im LiveView-Modul sparen, das sieht ja eh etwas hacky aus.

2021-04-16 11:44 UTC, preiaen commented on lib/erga_web/live/linked_resource_live.ex
> +    filter = if socket.assigns.linked_system == "thesaurus", do: %{use_hierarchy: true}, else: filter
Ja, ich hatte verschiedene Lösungen im Kopf. Und wollte erstmal den generellen Ansatz testen und zur Diskussion stellen. Das werde ich dann jetzt finalisieren.

2021-04-26 07:24 UTC, preiaen commented
Filter Funktion und Filter Parameter sind jetzt für Thesaurus ausgebaut.

2021-04-26 07:29 UTC, merged