External links#653
dainst/erga pull request #4
Opened 2020-09-08 12:59 UTC by njunghans

External links werden auch als Linked Resources betrachtet, wo nur die linked_id nil ist, und die linked_system auf "Other"

2020-09-08 14:35 UTC, dersmon requested changes
Das Interface würde ich auch fürn Prototypen noch ein bisschen verbessern. Ansonsten sind die Anmerkungen von mir diskussionswürdig, ich denke wir sollten uns bei Gelegenheit mal zusammensetzen und über das Coden von Elixir sprechen (gilt auch für meinen Pull-Request).

2020-09-08 14:35 UTC, dersmon commented on lib/erga_web/live/linked_resource_live/edit.ex
> +      |> assign(:search_error, "")
Wozu ist das gut?

2020-09-08 14:35 UTC, dersmon commented on lib/erga_web/services/service_helpers.ex
> +      "other" -> nil
Nil als Wert zurück zugeben riecht etwas nach code-smell (Bauchgefühl). Alternativvorschlag: Die Funktionen get_resource_name und loading_choosen_resource mit alternativen Signaturen (Pattern Matching) versehen, so dass "other" direkt als Spezialfall abgefangen wird. Dann könnte man sich auch die if-Abfrage in den Funktionen sparen.

2020-09-08 14:35 UTC, dersmon commented on lib/erga_web/live/linked_resource_live/show.ex
>    end
Ist `resId` für "other" nicht sowieso leer? Da könnte man direkt pattern matchen auf die Funktionsparameter.

2020-09-08 14:35 UTC, dersmon commented on lib/erga_web/live/linked_resource_live/edit.ex
> +    end
Man könnte auch system_name pattern matchen auf "other" und dafür einen eigenen Funktionsrumpf definieren. Dann spart man sich das handlen mit der if-Anweisung und die Bekanntmachung von "other" in ServiceHelpers.

2020-09-09 07:49 UTC, preiaen commented on lib/erga_web/services/service_helpers.ex
> +      "other" -> nil
Klingt nach der besseren Alternative.

2020-09-09 08:03 UTC, preiaen reviewed
Das ist jetzt vielleicht etwas blöd, aber ich weiß nicht ob die Lösung die linked_resources für die externen Links zu verwenden so eine glückliche Lösung ist. Es scheint mir, dass hier an vielen Stellen was umgebogen werden muss, weil es zweckentfremdet wird. Die Linked_Resources stellen zur Zeit eine Verknüpfung zu einem externen System über die dort verwendete ID her. Also quasi eine Systemübergreifende 1:N Beziehung. Die external Links sollten doch einfach nur Addressen auf externe Seiten speichern, oder verstehe ich das falsch? Hierfür wäre ein eigenes Modell und Controller die einfachere Lösung.

2020-09-09 08:05 UTC, preiaen commented on lib/erga_web/templates/linked_resource/form.html.leex
> +        <%= text_input f, :linked_resource_nam, value: @linked_val, phx_keyup: "search_resource" %>
Wo führt jetzt der search_resource event hin, wenn es keinen Service gibt?

2020-09-09 08:17 UTC, dersmon commented
> Das ist jetzt vielleicht etwas blöd, aber ich weiß nicht ob die Lösung die linked_resources für die externen Links zu verwenden so eine glückliche Lösung ist. Es scheint mir, dass hier an vielen Stellen was umgebogen werden muss, weil es zweckentfremdet wird. Die Linked_Resources stellen zur Zeit eine Verknüpfung zu einem externen System über die dort verwendete ID her. Also quasi eine Systemübergreifende 1:N Beziehung. Die external Links sollten doch einfach nur Addressen auf externe Seiten speichern, oder verstehe ich das falsch? Hierfür wäre ein eigenes Modell und Controller die einfachere Lösung.

Den Eindruck hatte ich auch. Wo schiebst du momentan die URL rein? Für URLs gibt es kein Datenbank-Feld.

2020-09-13 07:39 UTC, njunghans commented on lib/erga_web/live/linked_resource_live/edit.ex
> +      |> assign(:search_error, "")
Bug Fix, ohne dies gibt es ein search_error not found error sobald ein search error passiert

2020-09-13 08:31 UTC, njunghans commented on lib/erga_web/templates/linked_resource/form.html.leex
> +        <%= text_input f, :linked_resource_nam, value: @linked_val, phx_keyup: "search_resource" %>
der wird ja nicht aufgerufen, wegen der if klausel

2020-09-13 09:10 UTC, njunghans commented
Ein External Link ist konzeptuell eine externe ressource ohne ein Linked System, deshalb habe ich keinen weiteren datentyp eingebracht.
Falls das nicht zufrieden stellt, kann ich gerne die andere Variante durchführen.

2020-09-13 09:13 UTC, njunghans commented on lib/erga_web/live/linked_resource_live/edit.ex
> +    end
stimmt :)

2020-09-14 07:08 UTC, dersmon commented
Deine Änderung war nicht ganz das was ich meinte, habe meine Vorschlag gerade mal hochgeladen.

2020-09-14 07:09 UTC, dersmon commented
Abgesehen davon: Wo trägst du denn die URLs ein im Interface zu "anderen" Resourcen? Ich finde das ist jetzt alles konzeptionell nicht ganz klar. In Nils' implementation gab es gar kein Feld für URLs, da er lediglich das Zielsystem und die dortige ID gespeichert hat.

2020-09-17 13:02 UTC, njunghans commented
Design wird revidiert, deshalb close. Manche änderungen wurde in eigenstaendige_suche#684 branch übernommen.

2020-09-17 13:02 UTC, closed without merging