External url#685
dainst/erga pull request #5
Opened 2020-09-21 14:51 UTC by njunghans

2020-09-28 09:00 UTC, dersmon requested changes
Wenn wir das jetzt in zwei Tabellen und zwei MVC Komponenten trennen (linked resource vs. external url) gibt es eigentlich keinen Grund die external URL auch als "Live" Component umzusetzen. Ich würde mich da z.B. an den "standard MVC" der Bilder/Personen orientieren. Nils hatte für die linked resources diese Live Views für die Suche benutzt. Für einfache Links brauchen wir das nicht, oder?

2020-09-28 09:42 UTC, njunghans commented on README.md
> +
am besten beides dann. Ich brauchte das restart, das der server nicht auf dem docker zugreifen konnte.

2020-09-28 09:43 UTC, njunghans commented
> Wenn wir das jetzt in zwei Tabellen und zwei MVC Komponenten trennen (linked resource vs. external url) gibt es eigentlich keinen Grund die external URL auch als "Live" Component umzusetzen. Ich würde mich da z.B. an den "standard MVC" der Bilder/Personen orientieren. Nils hatte für die linked resources diese Live Views für die Suche benutzt. Für einfache Links brauchen wir das nicht, oder?

Die Live Componente gibt ja mehr Möglichkeiten. Ich gebe dir recht ich hätte mir Arbeit sparen können, aber da es jetzt schon da ist, macht es nicht Sinn es als live Komponente zu lassen ? oder hat es tatsächlich Nachteile ?

2020-09-28 11:29 UTC, preiaen commented on lib/erga_web/live/external_link_live/index.ex
> +      IO.inspect(project)
Diese IO.inspect Aufrufe können alle raus. Stehen die bei mir noch drin?

2020-09-28 11:31 UTC, preiaen commented on lib/erga_web/live/external_link_live/index.ex
> +  def handle_event("load_resources", %{"foo" => params}, socket) do
Foo ist vermutlich von den linked_ressources übernommen worden. Ich werde das dort noch ändern, das sollte hier auch geschehen.

2020-09-28 11:33 UTC, njunghans commented on lib/erga_web/live/external_link_live/index.ex
> +      IO.inspect(project)
oh ja das ist noch von deinem branch

2020-09-28 11:34 UTC, njunghans commented on lib/erga_web/live/external_link_live/index.ex
> +  def handle_event("load_resources", %{"foo" => params}, socket) do
am besten gleich hier oder ? dein branch würde ich schliessen da ich hier unsere gemerged habe

2020-09-28 11:47 UTC, preiaen commented on lib/erga_web/templates/project/form.html.eex
> +      <%= #link "remove", to: Routes.live_path(@conn, ErgaWeb.ExternalLinkLive.Index, resource), phx_click: "delete_resource", phx_value_id: resource.id, data: [confirm: "Are you sure?"] %>
Irgendwie muss man hier per Click den delete event in dem Index ausführen, ich weiß noch nicht wie das gehen soll, müsste aber noch geändert werden.

2020-09-28 11:49 UTC, preiaen requested changes
Es gibt ein paar kleine Änderungen die vermutlich von linked_ressources übernommen wurden und dort auch noch geändert werden müssen ( mache ich gleich ). Ansonsten sieht es gut aus.

2020-09-28 12:15 UTC, dersmon commented
> > Wenn wir das jetzt in zwei Tabellen und zwei MVC Komponenten trennen (linked resource vs. external url) gibt es eigentlich keinen Grund die external URL auch als "Live" Component umzusetzen. Ich würde mich da z.B. an den "standard MVC" der Bilder/Personen orientieren. Nils hatte für die linked resources diese Live Views für die Suche benutzt. Für einfache Links brauchen wir das nicht, oder?
> 
> Die Live Componente gibt ja mehr Möglichkeiten. Ich gebe dir recht ich hätte mir Arbeit sparen können, aber da es jetzt schon da ist, macht es nicht Sinn es als live Komponente zu lassen ? oder hat es tatsächlich Nachteile ?

Ich fände es ehrlich gesagt sauberer Live nur zu benutzen wo es auch benötigt wird. Sonst ist das für jemanden der sich später nochmal dran setzt etwas verwirrend und ich finde es auch komplexer rein vom code.

2020-10-13 14:26 UTC, dersmon requested changes
Gibt leider noch Merge-Konflikte, der Rest ist eher Kleinkram.

2020-10-13 14:26 UTC, dersmon commented on lib/erga_web/templates/project/form.html.eex
> +  </div>
Das kam bei edn Resources auch schon vor, aber wieso gibt es kein Delete? Aktuell ist man mit einmal angelegten Links gefangen bzw. muss da dann über die Link-Liste gehen und dort löschen? Bei den Stakeholdern hatte ich eigentlich was drin um die direkt im Edit des Projektes zu löschen.

2020-10-13 14:26 UTC, dersmon commented on lib/erga_web/templates/project/form.html.eex
> +      <%= resource.label %>, <%= resource.url %> |
Bisschen kleinkariert eventuell: Durch copy paste heißt das `resource` anstatt `external_link`.

2020-10-13 14:26 UTC, dersmon commented on lib/erga_web/templates/project/show.html.eex
> +<div><%= resource.label %> <small><%= resource.url %></small></div>
s.o. sauberer wäre `external_link` oder `link` statt `resource`.

2020-10-13 14:26 UTC, dersmon commented on lib/erga_web/views/external_link_view.ex
> +  alias ErgaWeb.ExternalLinkLive
Bin mir gerade nicht sicher wozu es diesen alias gibt, und wieso heißt der `...Live`?

2020-10-14 10:39 UTC, njunghans commented on lib/erga_web/views/external_link_view.ex
> +  alias ErgaWeb.ExternalLinkLive
good find :D ist ein relikt.

2020-10-14 11:08 UTC, merged