New translations
dainst/erga pull request #8
Opened 2020-10-12 12:30 UTC by preiaen

Ich habe jetzt Übersetzungen für Project Title und Descriptions eingebaut, d.h. ich habe die Tabellenstruktur angepasst und die Aufrufe in den Views Show und Index. 

Für die Auswahl der Sprache gibt es einen neuen Parameter ?lang=DE, wenn es den LanguageCode in der Liste der Translations nicht gibt, wird die erste Translation der Liste zurückgegeben, was dann hoffentlich Deutsch ist. 
Ich dachte erst per Default DE zurück zu geben, aber war mir nicht sicher, ob wir garantieren können, dass es das immer gibt. 

Wenn man ein Project oder die Projectliste direkt aufruft und die Lang Option nicht mit überträgt wird man an lang=DE weitergeleitet.

Was noch fehlt sind die Create-Formulare, bislang arbeite ich mit den seed-Daten. Ich will aber trotzdem schon mal eure Meinung zum Tabellenentwurf haben.

2020-10-12 12:50 UTC, njunghans approved these changes

2020-10-14 06:35 UTC, dersmon requested changes
Ich bekomme gerade:
```
ArgumentError at GET /projects/1/edit
lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %Erga.Research.TranslatedContent{__meta__: #Ecto.Schema.Metadata<:loaded, "translated_contents">, content: "Großartiges Ausgrabungsprojekt", id: 3, inserted_at: ~N[2020-10-14 06:32:40], language_code: "DE", updated_at: ~N[2020-10-14 06:32:40]}
```
Nachdem ich ein mix ecto.reset ausgeführt habe und das Dummy Projekt editieren wollte.

2020-10-14 13:46 UTC, preiaen commented
> Ich bekomme gerade:
> 
> ```
> ArgumentError at GET /projects/1/edit
> lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %Erga.Research.TranslatedContent{__meta__: #Ecto.Schema.Metadata<:loaded, "translated_contents">, content: "Großartiges Ausgrabungsprojekt", id: 3, inserted_at: ~N[2020-10-14 06:32:40], language_code: "DE", updated_at: ~N[2020-10-14 06:32:40]}
> ```
> 
> Nachdem ich ein mix ecto.reset ausgeführt habe und das Dummy Projekt editieren wollte.

In meiner aktuellen Version sollte es gehen.

2020-10-19 09:23 UTC, preiaen commented
@dersmon @njunghans Ich denke ich habe jetzt einen verwendbaren Stand, der auch keine Fehler mehr enthalten sollte.

2020-10-27 07:00 UTC, preiaen commented
@dersmon da steht, dass du Änderungen wünscht, aber ich kann nicht sehen welche.

2020-10-27 07:02 UTC, dersmon commented
Ich glaube das war noch von dem Error neulich. Du hast aber auch noch einen Branch conflict. Ich teste gerade mal ob es bei mir jetzt läuft.

2020-10-27 07:08 UTC, dersmon commented
Für diesen Pull-Request erstmal nicht so wichtig aber aktuell kann man z.B. mehrere Titel pro Projekt eingeben. Würde es Sinn machen das eventuell nochmal einzuschränken? Neues Ticket dann.

2020-10-27 07:19 UTC, dersmon requested changes
Nur eine Sache wegen der Anzeige.

2020-10-27 07:19 UTC, dersmon commented on lib/erga_web/templates/translated_content/form.html.eex
> +    </div>
Bei der Edit-Ansicht sind ja Dropdown und Textfeld nebeneinander. Bei mir verhält sich das etwas funky wenn man die Größe des Textfeldes ändert (z.B. stehen dann manchmal die Überschriften so direkt nebeneinander: "Language codeContent"). Könnte man das noch irgendwie fixen und evtl. die initiale Größe des Textfeldes auch etwas erhöhen?

2020-10-27 07:19 UTC, dersmon commented on lib/erga_web/templates/translated_content/form.html.eex
> +  <%= hidden_input f, :col_name, value: @col_name %>
Was hat es mit dem `col_name` als hidden input auf sich?

2020-10-27 07:24 UTC, dersmon commented on lib/erga_web/templates/translated_content/form.html.eex
> +    </div>
![ueberschrift_zusammen](https://user-images.githubusercontent.com/1241690/97269355-b1c4ed00-182d-11eb-9cf6-c91a12b64e4c.png)

2020-10-27 10:17 UTC, preiaen commented on lib/erga_web/templates/translated_content/form.html.eex
> +  <%= hidden_input f, :col_name, value: @col_name %>
In col_name wird gespeichert, welche Column der Project Table übersetzt wird.  
Der Name ist etwas unglücklich, aber mir ist nichts besseres Eingefallen. In Projects können sowohl der Titel als auch die Beschreibung übersetzt werden und irgendwie muss man die auseinanderhalten.

2020-10-27 10:18 UTC, preiaen commented on lib/erga_web/templates/translated_content/form.html.eex
> +    </div>
Ich kann nochmal schauen, ob man bei dem Css-Grid ein Min value angeben kann.

2020-10-27 10:19 UTC, preiaen commented
> Für diesen Pull-Request erstmal nicht so wichtig aber aktuell kann man z.B. mehrere Titel pro Projekt eingeben. Würde es Sinn machen das eventuell nochmal einzuschränken? Neues Ticket dann.

Man bräuchte eine Unique Constraint, dass man nur einen Title pro Language Code angeben kanne.

2020-10-27 10:37 UTC, preiaen commented on lib/erga_web/templates/translated_content/form.html.eex
> +    </div>
die css-classes haben einfach nicht gestimmt, ist gefixed. col ist Bootstrap bei milligram muss man column ausschreiben

2020-10-27 11:24 UTC, preiaen commented
Habe die Konflikte behoben.

2020-10-27 13:24 UTC, merged